mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "ML_Pipeline_Experiments"

log_path: "ML_Scripts/Linear_Regression/linear_regression_project/Reports/logs.log"
data_path: "ML_Scripts/data/College.csv"
new_data_path: "ML_Scripts/data/New_College.csv"
target_column: "Grad.Rate"
reports_path: "ML_Scripts/Linear_Regression/linear_regression_project/Reports"
eda_tool: 
  tool: "ydata-profiling"  # Options: 'sweetviz', 'ydata-profiling', 'dtale'
  open_browser: false  # Option to open D-Tale in the browser
outlier_detection:
  ml_models:
    isolation_forest:
      n_estimators: 100
      max_samples: "auto"
      contamination: 0.1
      random_state: 42
outlier_strategy: "remove"  # Options: 'remove', 'cap', 'transform'
feature_engineering:
  scaler: "StandardScaler"
  generate_synthetic_features: false  # Add this key if synthetic features are optional
  perform_feature_selection: true  # Add this key if feature selection is optional
feature_selection:
  method: correlation_threshold  # Valid methods: 'variance_threshold', 'correlation_threshold'
  threshold: 0.1
optuna:
  n_trials: 50
grid_search:
  param_grid:
    model__alpha: [0.01, 0.1, 1, 10]
    model__fit_intercept: [True, False]
split_type: "train_test"  # Options: 'train_test', 'k_fold', 'time_series'
flaml:
  time_budget: 600  # Set the time budget for FLAML in seconds
  metric: 'r2'  # Metric to optimize
  task: 'regression'  # Task type
  estimator_list: ['lgbm', 'xgboost', 'rf', 'catboost']  
  mem_thres: 0.8  # Set memory threshold to 80%
  learner_kwargs:
    lgbm:
      num_leaves: 31
      max_depth: -1
      n_estimators: 100
drift_detection:
  ks_test_p_val: 0.05  # P-value threshold for Kolmogorov-Smirnov test
  chi2_test_p_val: 0.05  # P-value threshold for Chi-Square test
  js_divergence_threshold: 0.1  # Threshold for Jensen-Shannon divergence
  alibi_ks_p_val: 0.05  # P-value threshold for Alibi Detect KSDrift
  alibi_chi2_p_val: 0.05  # P-value threshold for Alibi Detect ChiSquareDrift
  evidently:
    report_path: "ML_Scripts/Linear_Regression/linear_regression_project/Reports/evidently_report.html"