experiment_name: insurance_v3_azure
preset: production
task_type: regression

dataset:
  name: insurance
  target_column: charges
  blob_path: insurance.csv
  datastore_name: mlops_blob

azureml:
  subscription_id: <AZURE_SUBSCRIPTION_ID>
  resource_group: <AZURE_RESOURCE_GROUP>
  workspace_name: <AZURE_WORKSPACE_NAME>
  compute_target: <AZURE_COMPUTE>
  environment_name_preprocessing: mlops-v3-preprocessing
  environment_name_training: mlops-v3-training

recipes:
  - file: recipes/baseline_recipe.yml
