experiment_name: length_of_stay_v3_azure
preset: production
task_type: regression

dataset:
  name: length_of_stay
  target_column: lengthofstay
  blob_path: LengthOfStay.csv
  datastore_name: mlops_blob

azureml:
  subscription_id: <AZURE_SUBSCRIPTION_ID>
  resource_group: <AZURE_RESOURCE_GROUP>
  workspace_name: <AZURE_WORKSPACE_NAME>
  compute_target: <AZURE_COMPUTE>
  environment_name_preprocessing: mlops-v3-preprocessing
  environment_name_training: mlops-v3-training

recipes:
  - file: recipes/baseline_recipe.yml
